#!/usr/bin/env python3

import argparse
import math
import uuid
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


IMAGE_SIZE = (1536, 1024)
PLAYABLE_RECT = (141.0, 159.3125, 1254.0, 705.375)
LEVEL_NAME = "Dorchester Heights"
UUID_NAMESPACE = uuid.UUID("17914ebc-7052-490d-b606-afc1746da512")

# The planned British assault would have crossed from Castle Island and struck
# the eastern flank. Both game routes follow that landing road, then divide at
# the saddle to threaten the two separately fortified hills.
PATH_CONTROL_POINTS = (
    (
        (1580.0, 910.0),
        (1510.0, 865.0),
        (1435.0, 820.0),
        (1350.0, 775.0),
        (1260.0, 710.0),
        (1170.0, 615.0),
        (1090.0, 570.0),
        (1020.0, 540.0),
        (965.0, 515.0),
        (910.0, 496.0),
        (850.0, 482.0),
        (785.0, 476.0),
        (720.0, 474.0),
        (655.0, 481.0),
        (590.0, 480.0),
        (530.0, 466.0),
        (480.0, 445.0),
        (420.0, 416.0),
        (390.0, 380.0),
        (378.0, 337.0),
        (374.0, 292.0),
        (365.0, 248.0),
        (352.0, 207.0),
        (330.0, 169.0),
        (310.0, 132.0),
        (300.0, 90.0),
    ),
    (
        (1580.0, 910.0),
        (1510.0, 865.0),
        (1435.0, 820.0),
        (1350.0, 775.0),
        (1260.0, 710.0),
        (1170.0, 615.0),
        (1090.0, 570.0),
        (1020.0, 540.0),
        (965.0, 515.0),
        (910.0, 496.0),
        (850.0, 482.0),
        (785.0, 476.0),
        (720.0, 474.0),
        (765.0, 466.0),
        (825.0, 460.0),
        (875.0, 440.0),
        (905.0, 410.0),
        (915.0, 370.0),
        (910.0, 325.0),
        (895.0, 285.0),
        (864.0, 247.0),
        (840.0, 214.0),
        (815.0, 184.0),
        (797.0, 151.0),
        (788.0, 112.0),
        (790.0, 75.0),
    ),
)

# Centers of the ten painted fieldstone-and-timber foundations.
TOWER_SLOTS = (
    (448.0, 386.0),
    (840.0, 410.0),
    (1004.0, 405.0),
    (335.0, 467.0),
    (472.0, 511.0),
    (1105.0, 507.0),
    (893.0, 545.0),
    (611.0, 625.0),
    (966.0, 643.0),
    (1118.0, 659.0),
)

UNLOCKS = (
    ("ranged", 3),
    ("melee", 2),
    ("artillery", 1),
)


def catmull_rom(
    points: tuple[tuple[float, float], ...],
    samples_per_segment: int = 24,
) -> list[tuple[float, float]]:
    samples = []
    padded = (points[0],) + points + (points[-1],)
    for index in range(1, len(padded) - 2):
        p0, p1, p2, p3 = padded[index - 1 : index + 3]
        for sample in range(samples_per_segment):
            t = sample / samples_per_segment
            t2 = t * t
            t3 = t2 * t
            x = 0.5 * (
                2 * p1[0]
                + (-p0[0] + p2[0]) * t
                + (2 * p0[0] - 5 * p1[0] + 4 * p2[0] - p3[0]) * t2
                + (-p0[0] + 3 * p1[0] - 3 * p2[0] + p3[0]) * t3
            )
            y = 0.5 * (
                2 * p1[1]
                + (-p0[1] + p2[1]) * t
                + (2 * p0[1] - 5 * p1[1] + 4 * p2[1] - p3[1]) * t2
                + (-p0[1] + 3 * p1[1] - 3 * p2[1] + p3[1]) * t3
            )
            samples.append((x, y))
    samples.append(points[-1])
    return samples


def resample(
    points: list[tuple[float, float]],
    spacing: float = 3.0,
) -> list[tuple[float, float]]:
    result = [points[0]]
    distance_to_next = spacing
    previous = points[0]

    for current in points[1:]:
        segment_x = current[0] - previous[0]
        segment_y = current[1] - previous[1]
        segment_length = math.hypot(segment_x, segment_y)
        if segment_length == 0:
            continue

        while segment_length >= distance_to_next:
            ratio = distance_to_next / segment_length
            point = (
                previous[0] + segment_x * ratio,
                previous[1] + segment_y * ratio,
            )
            result.append(point)
            previous = point
            segment_x = current[0] - previous[0]
            segment_y = current[1] - previous[1]
            segment_length = math.hypot(segment_x, segment_y)
            distance_to_next = spacing

        distance_to_next -= segment_length
        previous = current

    if result[-1] != points[-1]:
        result.append(points[-1])
    return result


def stable_id(kind: str, *parts: object) -> str:
    key = "-".join((kind, *(str(part) for part in parts)))
    return str(uuid.uuid5(UUID_NAMESPACE, key))


def sql_rows(paths: tuple[list[tuple[float, float]], ...]) -> str:
    lines = [
        "-- Generated by Tools/generate_dorchester_heights_level.py.",
        "-- The eastern landing route divides at the saddle toward both hills.",
        "BEGIN TRANSACTION;",
        "",
        "DELETE FROM level_path_point",
        f"WHERE level_info_id = (SELECT id FROM level_info WHERE level_name = '{LEVEL_NAME}');",
        "DELETE FROM tower_slot",
        f"WHERE level_info_id = (SELECT id FROM level_info WHERE level_name = '{LEVEL_NAME}');",
        "DELETE FROM level_tower_unlock",
        f"WHERE level_info_id = (SELECT id FROM level_info WHERE level_name = '{LEVEL_NAME}');",
        "",
    ]

    for path_index, points in enumerate(paths):
        lines.extend(
            [
                "INSERT INTO level_path_point (",
                "    id, level_info_id, path_index, point_index,",
                "    map_position_x, map_position_y",
                ") VALUES",
            ]
        )
        for point_index, (x, y) in enumerate(points):
            suffix = ";" if point_index == len(points) - 1 else ","
            lines.append(
                "('"
                + stable_id("path", path_index, point_index)
                + "', (SELECT id FROM level_info WHERE level_name = '"
                + LEVEL_NAME
                + f"'), {path_index}, {point_index}, {x:.1f}, {y:.1f}){suffix}"
            )
        lines.append("")

    lines.extend(
        [
            "INSERT INTO tower_slot (",
            "    id, level_info_id, map_position_x, map_position_y",
            ") VALUES",
        ]
    )
    for index, (x, y) in enumerate(TOWER_SLOTS):
        suffix = ";" if index == len(TOWER_SLOTS) - 1 else ","
        lines.append(
            "('"
            + stable_id("slot", index)
            + "', (SELECT id FROM level_info WHERE level_name = '"
            + LEVEL_NAME
            + f"'), {x:.1f}, {y:.1f}){suffix}"
        )

    lines.extend(
        [
            "",
            "INSERT INTO level_tower_unlock (",
            "    id, level_info_id, tower_kind, max_tower_level",
            ") VALUES",
        ]
    )
    for index, (tower_kind, max_level) in enumerate(UNLOCKS):
        suffix = ";" if index == len(UNLOCKS) - 1 else ","
        lines.append(
            "('"
            + stable_id("unlock", tower_kind)
            + "', (SELECT id FROM level_info WHERE level_name = '"
            + LEVEL_NAME
            + f"'), '{tower_kind}', {max_level}){suffix}"
        )
    lines.extend(("", "COMMIT;", ""))
    return "\n".join(lines)


def draw_qa_overlay(
    image_path: Path,
    output_path: Path,
    paths: tuple[list[tuple[float, float]], ...],
) -> None:
    with Image.open(image_path) as source:
        image = source.convert("RGBA")
    overlay = Image.new("RGBA", image.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(overlay)
    x, y, width, height = PLAYABLE_RECT
    draw.rectangle(
        (x, y, x + width, y + height),
        outline=(92, 255, 146, 255),
        width=6,
    )

    colors = ((255, 80, 72, 235), (78, 166, 255, 235))
    for path_index, points in enumerate(paths):
        draw.line(points, fill=(24, 18, 15, 215), width=15, joint="curve")
        draw.line(points, fill=colors[path_index], width=8, joint="curve")

    font = ImageFont.truetype(
        "/System/Library/Fonts/Supplemental/Arial Bold.ttf",
        22,
    )
    for index, (slot_x, slot_y) in enumerate(TOWER_SLOTS, start=1):
        radius = 34
        draw.ellipse(
            (
                slot_x - radius,
                slot_y - radius,
                slot_x + radius,
                slot_y + radius,
            ),
            outline=(255, 245, 94, 255),
            width=5,
        )
        draw.text(
            (slot_x, slot_y),
            str(index),
            font=font,
            fill=(255, 255, 255, 255),
            stroke_width=3,
            stroke_fill=(31, 25, 18, 255),
            anchor="mm",
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    Image.alpha_composite(image, overlay).convert("RGB").save(output_path, "PNG")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate Dorchester Heights seed SQL and an optional QA overlay."
    )
    parser.add_argument(
        "--sql-output",
        type=Path,
        default=Path(__file__).parent.parent
        / "Db"
        / "DML"
        / "dorchester_heights_level.sql",
    )
    parser.add_argument("--image", type=Path)
    parser.add_argument("--overlay-output", type=Path)
    arguments = parser.parse_args()
    if (arguments.image is None) != (arguments.overlay_output is None):
        parser.error("--image and --overlay-output must be supplied together")
    return arguments


if __name__ == "__main__":
    args = parse_args()
    paths = tuple(
        resample(catmull_rom(control_points))
        for control_points in PATH_CONTROL_POINTS
    )
    args.sql_output.parent.mkdir(parents=True, exist_ok=True)
    args.sql_output.write_text(sql_rows(paths), encoding="utf-8")
    if args.image is not None:
        draw_qa_overlay(args.image, args.overlay_output, paths)
