#!/usr/bin/env python3

import argparse
import math
import uuid
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


IMAGE_SIZE = (1536, 1024)
PLAYABLE_RECT = (141.0, 159.3125, 1254.0, 705.375)
LEVEL_NAME = "Kettle Creek"
UUID_NAMESPACE = uuid.UUID("33d900c6-c6ff-409a-973b-f09ddc8a6f6a")

# Both routes follow the painted roads. The first descends War Hill through
# Boyd's breastwork; the second sweeps through the eastern canebrake. They join
# at the rocky ford and share the historical Loyalist withdrawal route.
PATH_CONTROL_POINTS = (
    (
        (758.0, -45.0),
        (756.0, 65.0),
        (752.0, 165.0),
        (754.0, 270.0),
        (746.0, 365.0),
        (765.0, 455.0),
        (795.0, 525.0),
        (810.0, 575.0),
        (802.0, 625.0),
        (850.0, 680.0),
        (935.0, 720.0),
        (1045.0, 765.0),
        (1165.0, 825.0),
        (1300.0, 900.0),
        (1445.0, 980.0),
        (1570.0, 1050.0),
    ),
    (
        (1365.0, -45.0),
        (1355.0, 65.0),
        (1338.0, 170.0),
        (1305.0, 275.0),
        (1255.0, 375.0),
        (1175.0, 455.0),
        (1080.0, 510.0),
        (980.0, 548.0),
        (890.0, 568.0),
        (810.0, 575.0),
        (802.0, 625.0),
        (850.0, 680.0),
        (935.0, 720.0),
        (1045.0, 765.0),
        (1165.0, 825.0),
        (1300.0, 900.0),
        (1445.0, 980.0),
        (1570.0, 1050.0),
    ),
)

# Centers of the ten painted fieldstone-and-timber foundations.
TOWER_SLOTS = (
    (525.0, 241.0),
    (558.0, 346.0),
    (947.0, 258.0),
    (886.0, 354.0),
    (205.0, 523.0),
    (1148.0, 521.0),
    (1284.0, 601.0),
    (480.0, 720.0),
    (824.0, 790.0),
    (1112.0, 739.0),
)

UNLOCKS = (
    ("ranged", 3),
    ("melee", 2),
    ("artillery", 1),
)


def catmull_rom(
    points: tuple[tuple[float, float], ...],
    samples_per_segment: int = 24,
) -> list[tuple[float, float]]:
    samples = []
    padded = (points[0],) + points + (points[-1],)
    for index in range(1, len(padded) - 2):
        p0, p1, p2, p3 = padded[index - 1 : index + 3]
        for sample in range(samples_per_segment):
            t = sample / samples_per_segment
            t2 = t * t
            t3 = t2 * t
            x = 0.5 * (
                2 * p1[0]
                + (-p0[0] + p2[0]) * t
                + (2 * p0[0] - 5 * p1[0] + 4 * p2[0] - p3[0]) * t2
                + (-p0[0] + 3 * p1[0] - 3 * p2[0] + p3[0]) * t3
            )
            y = 0.5 * (
                2 * p1[1]
                + (-p0[1] + p2[1]) * t
                + (2 * p0[1] - 5 * p1[1] + 4 * p2[1] - p3[1]) * t2
                + (-p0[1] + 3 * p1[1] - 3 * p2[1] + p3[1]) * t3
            )
            samples.append((x, y))
    samples.append(points[-1])
    return samples


def resample(
    points: list[tuple[float, float]],
    spacing: float = 3.0,
) -> list[tuple[float, float]]:
    result = [points[0]]
    distance_to_next = spacing
    previous = points[0]

    for current in points[1:]:
        segment_x = current[0] - previous[0]
        segment_y = current[1] - previous[1]
        segment_length = math.hypot(segment_x, segment_y)
        if segment_length == 0:
            continue

        while segment_length >= distance_to_next:
            ratio = distance_to_next / segment_length
            point = (
                previous[0] + segment_x * ratio,
                previous[1] + segment_y * ratio,
            )
            result.append(point)
            previous = point
            segment_x = current[0] - previous[0]
            segment_y = current[1] - previous[1]
            segment_length = math.hypot(segment_x, segment_y)
            distance_to_next = spacing

        distance_to_next -= segment_length
        previous = current

    if result[-1] != points[-1]:
        result.append(points[-1])
    return result


def stable_id(kind: str, *parts: object) -> str:
    key = "-".join((kind, *(str(part) for part in parts)))
    return str(uuid.uuid5(UUID_NAMESPACE, key))


def sql_rows(paths: tuple[list[tuple[float, float]], ...]) -> str:
    lines = [
        "-- Generated by Tools/generate_kettle_creek_level.py.",
        "-- Two routes converge at the Kettle Creek ford and share one exit.",
        "BEGIN TRANSACTION;",
        "",
        "DELETE FROM level_path_point",
        f"WHERE level_info_id = (SELECT id FROM level_info WHERE level_name = '{LEVEL_NAME}');",
        "DELETE FROM tower_slot",
        f"WHERE level_info_id = (SELECT id FROM level_info WHERE level_name = '{LEVEL_NAME}');",
        "DELETE FROM level_tower_unlock",
        f"WHERE level_info_id = (SELECT id FROM level_info WHERE level_name = '{LEVEL_NAME}');",
        "",
    ]

    for path_index, points in enumerate(paths):
        lines.extend(
            [
                "INSERT INTO level_path_point (",
                "    id, level_info_id, path_index, point_index,",
                "    map_position_x, map_position_y",
                ") VALUES",
            ]
        )
        for point_index, (x, y) in enumerate(points):
            suffix = ";" if point_index == len(points) - 1 else ","
            lines.append(
                "('"
                + stable_id("path", path_index, point_index)
                + "', (SELECT id FROM level_info WHERE level_name = '"
                + LEVEL_NAME
                + f"'), {path_index}, {point_index}, {x:.1f}, {y:.1f}){suffix}"
            )
        lines.append("")

    lines.extend(
        [
            "INSERT INTO tower_slot (",
            "    id, level_info_id, map_position_x, map_position_y",
            ") VALUES",
        ]
    )
    for index, (x, y) in enumerate(TOWER_SLOTS):
        suffix = ";" if index == len(TOWER_SLOTS) - 1 else ","
        lines.append(
            "('"
            + stable_id("slot", index)
            + "', (SELECT id FROM level_info WHERE level_name = '"
            + LEVEL_NAME
            + f"'), {x:.1f}, {y:.1f}){suffix}"
        )

    lines.extend(
        [
            "",
            "INSERT INTO level_tower_unlock (",
            "    id, level_info_id, tower_kind, max_tower_level",
            ") VALUES",
        ]
    )
    for index, (tower_kind, max_level) in enumerate(UNLOCKS):
        suffix = ";" if index == len(UNLOCKS) - 1 else ","
        lines.append(
            "('"
            + stable_id("unlock", tower_kind)
            + "', (SELECT id FROM level_info WHERE level_name = '"
            + LEVEL_NAME
            + f"'), '{tower_kind}', {max_level}){suffix}"
        )
    lines.extend(("", "COMMIT;", ""))
    return "\n".join(lines)


def draw_qa_overlay(
    image_path: Path,
    output_path: Path,
    paths: tuple[list[tuple[float, float]], ...],
) -> None:
    with Image.open(image_path) as source:
        image = source.convert("RGBA")
    overlay = Image.new("RGBA", image.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(overlay)
    x, y, width, height = PLAYABLE_RECT
    draw.rectangle(
        (x, y, x + width, y + height),
        outline=(92, 255, 146, 255),
        width=6,
    )

    colors = ((255, 80, 72, 235), (78, 166, 255, 235))
    for path_index, points in enumerate(paths):
        draw.line(points, fill=(24, 18, 15, 215), width=15, joint="curve")
        draw.line(points, fill=colors[path_index], width=8, joint="curve")

    font = ImageFont.truetype(
        "/System/Library/Fonts/Supplemental/Arial Bold.ttf",
        22,
    )
    for index, (slot_x, slot_y) in enumerate(TOWER_SLOTS, start=1):
        radius = 34
        draw.ellipse(
            (
                slot_x - radius,
                slot_y - radius,
                slot_x + radius,
                slot_y + radius,
            ),
            outline=(255, 245, 94, 255),
            width=5,
        )
        draw.text(
            (slot_x, slot_y),
            str(index),
            font=font,
            fill=(255, 255, 255, 255),
            stroke_width=3,
            stroke_fill=(31, 25, 18, 255),
            anchor="mm",
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    Image.alpha_composite(image, overlay).convert("RGB").save(output_path, "PNG")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate Kettle Creek seed SQL and an optional QA overlay."
    )
    parser.add_argument(
        "--sql-output",
        type=Path,
        default=Path(__file__).parent.parent / "Db" / "DML" / "kettle_creek_level.sql",
    )
    parser.add_argument("--image", type=Path)
    parser.add_argument("--overlay-output", type=Path)
    arguments = parser.parse_args()
    if (arguments.image is None) != (arguments.overlay_output is None):
        parser.error("--image and --overlay-output must be supplied together")
    return arguments


if __name__ == "__main__":
    args = parse_args()
    paths = tuple(
        resample(catmull_rom(control_points))
        for control_points in PATH_CONTROL_POINTS
    )
    args.sql_output.parent.mkdir(parents=True, exist_ok=True)
    args.sql_output.write_text(sql_rows(paths), encoding="utf-8")
    if args.image is not None:
        draw_qa_overlay(args.image, args.overlay_output, paths)
