#!/usr/bin/env python3

import argparse
import math
import uuid
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


IMAGE_SIZE = (1536, 1024)
PLAYABLE_RECT = (141.0, 150.3125, 1254.0, 705.375)
LEVEL_ID = "96170d0e-6983-47e0-bf80-93cd4c91ad3a"
UUID_NAMESPACE = uuid.UUID(LEVEL_ID)

# Garth's western division advanced inland from Savin Rock while Tryon's
# eastern division moved from Lighthouse Point toward Beacon Hill. Controls
# are authored north-to-south for visual tracing, then reversed for gameplay
# so enemies advance inland from the lower shoreline.
PATH_CONTROL_POINTS = (
    (
        (500.0, -45.0),
        (492.0, 30.0),
        (470.0, 90.0),
        (440.0, 145.0),
        (415.0, 205.0),
        (402.0, 270.0),
        (388.0, 330.0),
        (365.0, 390.0),
        (338.0, 450.0),
        (307.0, 515.0),
        (280.0, 580.0),
        (255.0, 645.0),
        (225.0, 710.0),
        (188.0, 775.0),
        (142.0, 840.0),
        (88.0, 905.0),
        (28.0, 970.0),
        (-45.0, 1065.0),
    ),
    (
        (1075.0, -45.0),
        (1082.0, 35.0),
        (1092.0, 100.0),
        (1102.0, 165.0),
        (1112.0, 230.0),
        (1124.0, 295.0),
        (1142.0, 355.0),
        (1175.0, 410.0),
        (1215.0, 450.0),
        (1248.0, 500.0),
        (1264.0, 560.0),
        (1279.0, 625.0),
        (1305.0, 690.0),
        (1342.0, 755.0),
        (1388.0, 820.0),
        (1442.0, 885.0),
        (1505.0, 955.0),
        (1580.0, 1065.0),
    ),
)

# Centers of the ten painted fieldstone foundations.
TOWER_SLOTS = (
    (512.0, 341.0),
    (667.0, 341.0),
    (834.0, 340.0),
    (989.0, 340.0),
    (488.0, 462.0),
    (659.0, 462.0),
    (826.0, 461.0),
    (998.0, 461.0),
    (660.0, 585.0),
    (835.0, 585.0),
)

UNLOCKS = (
    ("ranged", 3),
    ("melee", 2),
    ("artillery", 1),
)


def catmull_rom(
    points: tuple[tuple[float, float], ...],
    samples_per_segment: int = 24,
) -> list[tuple[float, float]]:
    samples = []
    padded = (points[0],) + points + (points[-1],)
    for index in range(1, len(padded) - 2):
        p0, p1, p2, p3 = padded[index - 1 : index + 3]
        for sample in range(samples_per_segment):
            t = sample / samples_per_segment
            t2 = t * t
            t3 = t2 * t
            x = 0.5 * (
                2 * p1[0]
                + (-p0[0] + p2[0]) * t
                + (2 * p0[0] - 5 * p1[0] + 4 * p2[0] - p3[0]) * t2
                + (-p0[0] + 3 * p1[0] - 3 * p2[0] + p3[0]) * t3
            )
            y = 0.5 * (
                2 * p1[1]
                + (-p0[1] + p2[1]) * t
                + (2 * p0[1] - 5 * p1[1] + 4 * p2[1] - p3[1]) * t2
                + (-p0[1] + 3 * p1[1] - 3 * p2[1] + p3[1]) * t3
            )
            samples.append((x, y))
    samples.append(points[-1])
    return samples


def resample(
    points: list[tuple[float, float]],
    spacing: float = 3.0,
) -> list[tuple[float, float]]:
    result = [points[0]]
    distance_to_next = spacing
    previous = points[0]

    for current in points[1:]:
        segment_x = current[0] - previous[0]
        segment_y = current[1] - previous[1]
        segment_length = math.hypot(segment_x, segment_y)
        if segment_length == 0:
            continue

        while segment_length >= distance_to_next:
            ratio = distance_to_next / segment_length
            point = (
                previous[0] + segment_x * ratio,
                previous[1] + segment_y * ratio,
            )
            result.append(point)
            previous = point
            segment_x = current[0] - previous[0]
            segment_y = current[1] - previous[1]
            segment_length = math.hypot(segment_x, segment_y)
            distance_to_next = spacing

        distance_to_next -= segment_length
        previous = current

    if result[-1] != points[-1]:
        result.append(points[-1])
    return result


def stable_id(kind: str, *parts: object) -> str:
    key = "-".join((kind, *(str(part) for part in parts)))
    return str(uuid.uuid5(UUID_NAMESPACE, key))


def sql_rows(paths: tuple[list[tuple[float, float]], ...]) -> str:
    lines = [
        "-- Generated by Tools/generate_new_haven_level.py.",
        "-- Two routes follow the western Garth and eastern Tryon divisions.",
        "BEGIN TRANSACTION;",
        "",
        "DELETE FROM level_path_point",
        f"WHERE level_info_id = '{LEVEL_ID}';",
        "DELETE FROM tower_slot",
        f"WHERE level_info_id = '{LEVEL_ID}';",
        "DELETE FROM level_tower_unlock",
        f"WHERE level_info_id = '{LEVEL_ID}';",
        "",
    ]

    for path_index, points in enumerate(paths):
        lines.extend(
            [
                "INSERT INTO level_path_point (",
                "    id, level_info_id, path_index, point_index,",
                "    map_position_x, map_position_y",
                ") VALUES",
            ]
        )
        for point_index, (x, y) in enumerate(points):
            suffix = ";" if point_index == len(points) - 1 else ","
            lines.append(
                f"('{stable_id('path', path_index, point_index)}', "
                f"'{LEVEL_ID}', {path_index}, {point_index}, {x:.1f}, {y:.1f})"
                + suffix
            )
        lines.append("")

    lines.extend(
        [
            "INSERT INTO tower_slot (",
            "    id, level_info_id, map_position_x, map_position_y",
            ") VALUES",
        ]
    )
    for index, (x, y) in enumerate(TOWER_SLOTS):
        suffix = ";" if index == len(TOWER_SLOTS) - 1 else ","
        lines.append(
            f"('{stable_id('slot', index)}', '{LEVEL_ID}', {x:.1f}, {y:.1f})"
            + suffix
        )

    lines.extend(
        [
            "",
            "INSERT INTO level_tower_unlock (",
            "    id, level_info_id, tower_kind, max_tower_level",
            ") VALUES",
        ]
    )
    for index, (tower_kind, max_level) in enumerate(UNLOCKS):
        suffix = ";" if index == len(UNLOCKS) - 1 else ","
        lines.append(
            f"('{stable_id('unlock', tower_kind)}', '{LEVEL_ID}', "
            f"'{tower_kind}', {max_level})"
            + suffix
        )
    lines.extend(("", "COMMIT;", ""))
    return "\n".join(lines)


def draw_qa_overlay(
    image_path: Path,
    output_path: Path,
    paths: tuple[list[tuple[float, float]], ...],
) -> None:
    with Image.open(image_path) as source:
        image = source.convert("RGBA")
    if image.size != IMAGE_SIZE:
        raise ValueError(f"Expected {IMAGE_SIZE}, found {image.size}")

    overlay = Image.new("RGBA", image.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(overlay)
    x, y, width, height = PLAYABLE_RECT
    draw.rectangle(
        (x, y, x + width, y + height),
        outline=(92, 255, 146, 255),
        width=6,
    )

    colors = ((255, 80, 72, 235), (78, 166, 255, 235))
    for path_index, points in enumerate(paths):
        draw.line(points, fill=(24, 18, 15, 215), width=15, joint="curve")
        draw.line(points, fill=colors[path_index], width=8, joint="curve")

    font = ImageFont.truetype(
        "/System/Library/Fonts/Supplemental/Arial Bold.ttf",
        22,
    )
    for index, (slot_x, slot_y) in enumerate(TOWER_SLOTS, start=1):
        radius = 34
        draw.ellipse(
            (
                slot_x - radius,
                slot_y - radius,
                slot_x + radius,
                slot_y + radius,
            ),
            outline=(255, 245, 94, 255),
            width=5,
        )
        draw.text(
            (slot_x, slot_y),
            str(index),
            font=font,
            fill=(255, 255, 255, 255),
            stroke_width=3,
            stroke_fill=(31, 25, 18, 255),
            anchor="mm",
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    Image.alpha_composite(image, overlay).convert("RGB").save(output_path, "PNG")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate New Haven seed SQL and an optional QA overlay."
    )
    parser.add_argument(
        "--sql-output",
        type=Path,
        default=Path(__file__).parent.parent
        / "Db"
        / "DML"
        / "new_haven_level.sql",
    )
    parser.add_argument("--image", type=Path)
    parser.add_argument("--overlay-output", type=Path)
    arguments = parser.parse_args()
    if (arguments.image is None) != (arguments.overlay_output is None):
        parser.error("--image and --overlay-output must be supplied together")
    return arguments


if __name__ == "__main__":
    args = parse_args()
    paths = tuple(
        resample(catmull_rom(tuple(reversed(control_points))))
        for control_points in PATH_CONTROL_POINTS
    )
    args.sql_output.parent.mkdir(parents=True, exist_ok=True)
    args.sql_output.write_text(sql_rows(paths), encoding="utf-8")
    if args.image is not None:
        draw_qa_overlay(args.image, args.overlay_output, paths)
