#!/usr/bin/env python3

import argparse
import math
import uuid
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


IMAGE_SIZE = (1536, 1024)
PLAYABLE_RECT = (141.0, 159.3125, 1254.0, 705.375)
LEVEL_ID = "42e95fce-6da1-416d-bf69-24f70bb4dc52"
UUID_NAMESPACE = uuid.UUID(LEVEL_ID)

# Hill's 9th Foot followed the Wood Creek military road, then occupied the
# wooded height. Both painted approaches converge on the road to Fort Anne.
PATH_CONTROL_POINTS = (
    (
        (238.0, -45.0),
        (238.0, 55.0),
        (214.0, 145.0),
        (185.0, 235.0),
        (170.0, 325.0),
        (180.0, 395.0),
        (240.0, 445.0),
        (335.0, 475.0),
        (430.0, 525.0),
        (525.0, 570.0),
        (615.0, 610.0),
        (700.0, 645.0),
        (730.0, 670.0),
        (820.0, 696.0),
        (910.0, 720.0),
        (1000.0, 748.0),
        (1090.0, 778.0),
        (1180.0, 810.0),
        (1280.0, 848.0),
        (1380.0, 892.0),
        (1480.0, 948.0),
        (1570.0, 1015.0),
    ),
    (
        (870.0, -45.0),
        (865.0, 55.0),
        (866.0, 145.0),
        (885.0, 230.0),
        (915.0, 315.0),
        (950.0, 395.0),
        (980.0, 470.0),
        (995.0, 540.0),
        (995.0, 600.0),
        (1010.0, 655.0),
        (1045.0, 705.0),
        (1090.0, 758.0),
        (1180.0, 810.0),
        (1280.0, 848.0),
        (1380.0, 892.0),
        (1480.0, 948.0),
        (1570.0, 1015.0),
    ),
)

# Centers of the ten painted fieldstone-and-timber foundations.
TOWER_SLOTS = (
    (1095.0, 370.0),
    (891.0, 438.0),
    (532.0, 445.0),
    (738.0, 454.0),
    (1138.0, 465.0),
    (625.0, 500.0),
    (819.0, 516.0),
    (282.0, 532.0),
    (273.0, 607.0),
    (402.0, 625.0),
)

UNLOCKS = (
    ("ranged", 3),
    ("melee", 2),
    ("artillery", 1),
)


def catmull_rom(
    points: tuple[tuple[float, float], ...],
    samples_per_segment: int = 24,
) -> list[tuple[float, float]]:
    samples = []
    padded = (points[0],) + points + (points[-1],)
    for index in range(1, len(padded) - 2):
        p0, p1, p2, p3 = padded[index - 1 : index + 3]
        for sample in range(samples_per_segment):
            t = sample / samples_per_segment
            t2 = t * t
            t3 = t2 * t
            x = 0.5 * (
                2 * p1[0]
                + (-p0[0] + p2[0]) * t
                + (2 * p0[0] - 5 * p1[0] + 4 * p2[0] - p3[0]) * t2
                + (-p0[0] + 3 * p1[0] - 3 * p2[0] + p3[0]) * t3
            )
            y = 0.5 * (
                2 * p1[1]
                + (-p0[1] + p2[1]) * t
                + (2 * p0[1] - 5 * p1[1] + 4 * p2[1] - p3[1]) * t2
                + (-p0[1] + 3 * p1[1] - 3 * p2[1] + p3[1]) * t3
            )
            samples.append((x, y))
    samples.append(points[-1])
    return samples


def resample(
    points: list[tuple[float, float]],
    spacing: float = 3.0,
) -> list[tuple[float, float]]:
    result = [points[0]]
    distance_to_next = spacing
    previous = points[0]

    for current in points[1:]:
        segment_x = current[0] - previous[0]
        segment_y = current[1] - previous[1]
        segment_length = math.hypot(segment_x, segment_y)
        if segment_length == 0:
            continue

        while segment_length >= distance_to_next:
            ratio = distance_to_next / segment_length
            point = (
                previous[0] + segment_x * ratio,
                previous[1] + segment_y * ratio,
            )
            result.append(point)
            previous = point
            segment_x = current[0] - previous[0]
            segment_y = current[1] - previous[1]
            segment_length = math.hypot(segment_x, segment_y)
            distance_to_next = spacing

        distance_to_next -= segment_length
        previous = current

    if result[-1] != points[-1]:
        result.append(points[-1])
    return result


def stable_id(kind: str, *parts: object) -> str:
    key = "-".join((kind, *(str(part) for part in parts)))
    return str(uuid.uuid5(UUID_NAMESPACE, key))


def sql_rows(paths: tuple[list[tuple[float, float]], ...]) -> str:
    lines = [
        "-- Generated by Tools/generate_fort_ann_level.py.",
        "-- Two routes converge along Wood Creek before the Fort Anne approach.",
        "BEGIN TRANSACTION;",
        "",
        "DELETE FROM level_path_point",
        f"WHERE level_info_id = '{LEVEL_ID}';",
        "DELETE FROM tower_slot",
        f"WHERE level_info_id = '{LEVEL_ID}';",
        "DELETE FROM level_tower_unlock",
        f"WHERE level_info_id = '{LEVEL_ID}';",
        "",
    ]

    for path_index, points in enumerate(paths):
        lines.extend(
            [
                "INSERT INTO level_path_point (",
                "    id, level_info_id, path_index, point_index,",
                "    map_position_x, map_position_y",
                ") VALUES",
            ]
        )
        for point_index, (x, y) in enumerate(points):
            suffix = ";" if point_index == len(points) - 1 else ","
            lines.append(
                f"('{stable_id('path', path_index, point_index)}', "
                f"'{LEVEL_ID}', {path_index}, {point_index}, {x:.1f}, {y:.1f})"
                + suffix
            )
        lines.append("")

    lines.extend(
        [
            "INSERT INTO tower_slot (",
            "    id, level_info_id, map_position_x, map_position_y",
            ") VALUES",
        ]
    )
    for index, (x, y) in enumerate(TOWER_SLOTS):
        suffix = ";" if index == len(TOWER_SLOTS) - 1 else ","
        lines.append(
            f"('{stable_id('slot', index)}', '{LEVEL_ID}', {x:.1f}, {y:.1f})"
            + suffix
        )

    lines.extend(
        [
            "",
            "INSERT INTO level_tower_unlock (",
            "    id, level_info_id, tower_kind, max_tower_level",
            ") VALUES",
        ]
    )
    for index, (tower_kind, max_level) in enumerate(UNLOCKS):
        suffix = ";" if index == len(UNLOCKS) - 1 else ","
        lines.append(
            f"('{stable_id('unlock', tower_kind)}', '{LEVEL_ID}', "
            f"'{tower_kind}', {max_level})"
            + suffix
        )
    lines.extend(("", "COMMIT;", ""))
    return "\n".join(lines)


def draw_qa_overlay(
    image_path: Path,
    output_path: Path,
    paths: tuple[list[tuple[float, float]], ...],
) -> None:
    with Image.open(image_path) as source:
        image = source.convert("RGBA")
    if image.size != IMAGE_SIZE:
        raise ValueError(f"Expected {IMAGE_SIZE}, found {image.size}")

    overlay = Image.new("RGBA", image.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(overlay)
    x, y, width, height = PLAYABLE_RECT
    draw.rectangle(
        (x, y, x + width, y + height),
        outline=(92, 255, 146, 255),
        width=6,
    )

    colors = ((255, 80, 72, 235), (78, 166, 255, 235))
    for path_index, points in enumerate(paths):
        draw.line(points, fill=(24, 18, 15, 215), width=15, joint="curve")
        draw.line(points, fill=colors[path_index], width=8, joint="curve")

    font = ImageFont.truetype(
        "/System/Library/Fonts/Supplemental/Arial Bold.ttf",
        22,
    )
    for index, (slot_x, slot_y) in enumerate(TOWER_SLOTS, start=1):
        radius = 34
        draw.ellipse(
            (
                slot_x - radius,
                slot_y - radius,
                slot_x + radius,
                slot_y + radius,
            ),
            outline=(255, 245, 94, 255),
            width=5,
        )
        draw.text(
            (slot_x, slot_y),
            str(index),
            font=font,
            fill=(255, 255, 255, 255),
            stroke_width=3,
            stroke_fill=(31, 25, 18, 255),
            anchor="mm",
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    Image.alpha_composite(image, overlay).convert("RGB").save(output_path, "PNG")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate Fort Ann seed SQL and an optional QA overlay."
    )
    parser.add_argument(
        "--sql-output",
        type=Path,
        default=Path(__file__).parent.parent
        / "Db"
        / "DML"
        / "fort_ann_level.sql",
    )
    parser.add_argument("--image", type=Path)
    parser.add_argument("--overlay-output", type=Path)
    arguments = parser.parse_args()
    if (arguments.image is None) != (arguments.overlay_output is None):
        parser.error("--image and --overlay-output must be supplied together")
    return arguments


if __name__ == "__main__":
    args = parse_args()
    paths = tuple(
        resample(catmull_rom(control_points))
        for control_points in PATH_CONTROL_POINTS
    )
    args.sql_output.parent.mkdir(parents=True, exist_ok=True)
    args.sql_output.write_text(sql_rows(paths), encoding="utf-8")
    if args.image is not None:
        draw_qa_overlay(args.image, args.overlay_output, paths)
